In [102]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [103]:
res = requests.get("https://www.bankbazaar.com/reviews/hdfc-bank/all-products.html")

In [104]:
soup=BeautifulSoup(res.text,'lxml')

In [105]:
bank_name = []
Name_html = soup.find_all("div",{"class":"review-bank-title"})

In [106]:
for i in Name_html:
    bank_name.append(i.find("img").get("alt"))

In [107]:
Customer_name = []
Cus_name = soup.find_all(class_='js-author-name')

In [108]:
for i in Cus_name:
    Customer_name.append(i.text)

In [109]:
Reviews = []
Review_html = soup.find_all(class_="text_here review-desc-more")
for i in Review_html:
    Reviews.append(i.text)

In [110]:
Services=[]
Services_html=soup.find_all("a",{"class":"user-review-comment js-individual-title"})

In [111]:
for i in Services_html:
    Services.append(i.text)

In [112]:
dict1={'bank_name':bank_name,'Customer_name':Customer_name,'Reviews':Reviews,"Services":Services}

In [113]:
df = pd.DataFrame.from_dict(dict1)

In [114]:
df

,bank_name,Customer_name,Reviews,Services
0,HDFC Bank,S K,\n I have used ...,"""very good"""
1,HDFC Bank,KUMAR,\n HDFC credit ...,"""Good service"""
2,HDFC Bank,K,\n HDFC has don...,"""Good loan offer """
3,HDFC Bank,RAM,\n I have taken...,"""Good service"""
4,HDFC Bank,LAN,\n Even if I fo...,"""Good service"""
5,HDFC Bank,B K,\n I am using H...,"""Excellent service"""
6,HDFC Bank,RAM,\n I taken a pe...,"""Good service"""
7,HDFC Bank,MAHADEV,\n I have my sa...,"""Excellent service"""
8,HDFC Bank,MAHADEV,\n Choosing HDF...,"""Excellent card"""
9,HDFC Bank,A T,\n Being with H...,"""Good service"""
10,HDFC Bank,HARNEET,\n The best par...,"""Best service"""
11,HDFC Bank,PALASH SINGHA,\n I am holding...,"""Good service"""
12,HDFC Bank,D VENKATESH,\n I have taken...,"""Good Service"""
13,HDFC Bank,MOHAMMED A,\n I am using H...,"""Excellent service"""
14,HDFC Bank,P M,\n I am happy w...,"""Good bank"""
15,HDFC Bank,P K,\n I have been ...,"""Interst rate was high"""
16,HDFC Bank,M BADUSHA,\n I have taken...,"""Excellent service"""
17,review,M BADUSHA,\n I have taken...,"""Excellent Service"""
18,HDFC Bank,B,\n Since I don'...,"""Interest rate was high"""
19,HDFC Bank,N,"\n Since 2002, ...","""Good"""

In [116]:
df.drop(index=17,inplace=True)

In [117]:
df.tail(5)

,bank_name,Customer_name,Reviews,Services
14,HDFC Bank,P M,\n I am happy w...,"""Good bank"""
15,HDFC Bank,P K,\n I have been ...,"""Interst rate was high"""
16,HDFC Bank,M BADUSHA,\n I have taken...,"""Excellent service"""
18,HDFC Bank,B,\n Since I don'...,"""Interest rate was high"""
19,HDFC Bank,N,"\n Since 2002, ...","""Good"""